name: Deploy to AWS dev

on:
  workflow_dispatch: {}
  push:
    branches:
      - dev 

jobs:
  Build:
    runs-on: ["self-hosted", "dev"] # ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: |
          docker buildx create --name myapp
          docker buildx use myapp
          docker buildx build --platform linux/amd64,linux/arm64 -t myapp:latest .
      
      - name: Log in to Docker Hub (if needed)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push Docker image
  #       run: |
  #         cd /home/ubuntu/dev
  #         # git pull origin design-main
  #         docker build --no-cache -t andy081/myapp .
  #         docker push andy081/myapp:latest
          
      - name: Tag Docker Image
        run: docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest
        
  #     - name: Stop and remove old container (if exists)
  #       run: |
  #         docker stop myapp || true
  #         docker rm myapp || true
  #     - name: Remove old images
  #       run: |
  #         docker rmi -f andy081/myapp
  #     - name: Run Docker container
  #       run: |
  #         docker run -d --name myapp -p 8000:8000 andy081/myapp:latest
