name: Deploy to EC2

on:
  push:
    branches:
      - dev  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: |
          docker buildx create --name myapp
          docker buildx use myapp
          docker buildx build --platform linux/amd64,linux/arm64 -t myapp:latest .
      
      - name: Log in to Docker Hub (if needed)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image to Docker Hub (if needed)
        run: |
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
      
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 instance public IP or hostname
          username: ${{ secrets.EC2_USERNAME }}  # SSH username
          key: ${{ secrets.EC2_PRIVATE_KEY }}  # SSH private key
          source: "."  # Source directory or files to copy
          target: "/path/to/remote/directory"  # Target directory on EC2
      
      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 instance public IP or hostname
          username: ${{ secrets.EC2_USERNAME }}  # SSH username
          key: ${{ secrets.EC2_PRIVATE_KEY }}  # SSH private key
          port: 22
          script: |
            cd /path/to/remote/directory
            docker-compose down
            docker-compose up -d
